### ISSUE TITLE
Fails with an AttributeError

### ISSUE THREAD

**Issue by simonfrey** [legovaer/jsonnet-docblock-parser#2]
# Setup
Linux, Python 3.8 (Same problem on 3.6)

# Reproduction

Exectute `jdp --file service.jsonnet` with service.jsonnet being:

```jsonnet
{
  service:: {
    new(name, namespace, app, ports): {
      apiVersion: 'v1',
      kind: 'Service',
      metadata: {
        labels: {
          app: app,
          env: namespace,
        },
        name: name,
        namespace: namespace,
      },
      spec: {
        type: 'NodePort',
        selector: {
          app: app,
          env: namespace,
        },
        ports: ports,
      },
    },
  },
}
```

Same problem with: 
```
{
  service:: {
      /**
   * Returns whether the string a is prefixed by the string b.
   *
   * @param name The input string.
   * @param namespace The input string.
   * @param app The prefix.
   * @param ports The prefix.
   * @return true if string a is prefixed by the string b or false otherwise.
   */
    new(name, namespace, app, ports): {
      apiVersion: 'v1',
      kind: 'Service',
      metadata: {
        labels: {
          app: app,
          env: namespace,
        },
        name: name,
        namespace: namespace,
      },
      spec: {
        type: 'NodePort',
        selector: {
          app: app,
          env: namespace,
        },
        ports: ports,
      },
    },
  },
}
```

# Expected behavior

It should render something

# Actual behavior

It fails with following error:

```bash
Traceback (most recent call last):
  File "/usr/bin/jdp", line 5, in <module>
    parser.main()
  File "/home/l1am0/.local/lib/python3.8/site-packages/jsonnet_docblock_parser/parser.py", line 207, in main
    print(generator.parse_json(results))
  File "/home/l1am0/.local/lib/python3.8/site-packages/jsonnet_docblock_parser/generator.py", line 21, in parse_json
    output["docblocks"].append(docblock.render())
AttributeError: 'str' object has no attribute 'render'
```

**Comment by simonfrey** [comment]
Any update here? Do you have an idea why that does not work?

**Comment by simonfrey** [comment]
This is not fixed.

Same problem with the fix from yesterday: 
```
$ ./scripts/jdp -f my.libsonnet 
Traceback (most recent call last):
  File "./scripts/jdp", line 5, in <module>
    parser.main()
  File "/usr/lib/python3.8/site-packages/jsonnet_docblock_parser/parser.py", line 207, in main
    print(generator.parse_json(results))
  File "/usr/lib/python3.8/site-packages/jsonnet_docblock_parser/generator.py", line 21, in parse_json
    output["docblocks"].append(docblock.render())
AttributeError: 'str' object has no attribute 'render'
```

git log gives current head at master `fbea17ed90489cbc5eec09950b70595c4561738b`
